name: Set up languages
description: Set up ruby, javascript, and dependencies
runs:
  using: composite
  steps:
    - name: Set up Ruby
      uses: ./.github/actions/setup-ruby
    - name: Set up Javascript
      uses: ./.github/actions/setup-javascript
