backend:
  name: github
  repo: rahearn/nih-oite-experiments
  branch: netlify-cms
  base_url: http://localhost:3000
  auth_endpoint: /netlify/auth
publish_mode: editorial_workflow
media_folder: public/images
public_folder: /images
collections:
  - name: page
    label: "Page"
    folder: "_pages"
    create: true
    fields:
      - {label: "Title", name: "title"}
      - {label: "Body", name: "body", widget: "markdown"}
