name: jest tests

on: [pull_request]

jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: setup
        uses: ./.github/actions/setup-project
        with:
          rails_env: test

      - name: Run Jest
        run: yarn test
