name: Frontend linting

on:
  pull_request:
    paths:
      - "**/*.jsx?"
      - "**/*.s?css"

jobs:
  frontend-linting:
    name: Frontend linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Javascript
        uses: ./.github/actions/setup-javascript

      - name: Check JS
        run: yarn lint:js

      - name: Check CSS
        run: yarn lint:css
